kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: seldon-iris
spec:
  to:
    kind: Service
    name: iris-seldon-example
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
